-- For table REGION
ALTER TABLE tpch_2g.REGION
ADD PRIMARY KEY (R_REGIONKEY);

-- For table NATION
ALTER TABLE tpch_2g.NATION
ADD PRIMARY KEY (N_NATIONKEY);

ALTER TABLE tpch_100mb.NATION
ADD FOREIGN KEY (N_REGIONKEY) REFERENCES tpch.REGION(R_REGIONKEY);

-- For table PART
ALTER TABLE tpch_100mb.PART
ADD PRIMARY KEY (P_PARTKEY);

-- For table SUPPLIER
ALTER TABLE tpch_100mb.SUPPLIER
ADD PRIMARY KEY (S_SUPPKEY);

ALTER TABLE tpch_100mb.SUPPLIER
ADD FOREIGN KEY (S_NATIONKEY) REFERENCES tpch.NATION(N_NATIONKEY);

-- For table PARTSUPP
ALTER TABLE tpch_100mb.PARTSUPP
ADD PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY);

-- For table CUSTOMER
ALTER TABLE tpch_100mb.CUSTOMER
ADD PRIMARY KEY (C_CUSTKEY);

ALTER TABLE tpch_100mb.CUSTOMER
ADD FOREIGN KEY (C_NATIONKEY) REFERENCES tpch.NATION(N_NATIONKEY);

-- For table LINEITEM
ALTER TABLE tpch_100mb.LINEITEM
ADD PRIMARY KEY (L_ORDERKEY,L_LINENUMBER);

-- For table ORDERS
ALTER TABLE tpch_100mb.ORDERS
ADD PRIMARY KEY (O_ORDERKEY);

-- For table PARTSUPP
ALTER TABLE tpch_100mb.PARTSUPP
ADD FOREIGN KEY (PS_SUPPKEY) REFERENCES tpch.SUPPLIER(S_SUPPKEY),
ADD FOREIGN KEY (PS_PARTKEY) REFERENCES tpch.PART(P_PARTKEY);

-- For table ORDERS
ALTER TABLE tpch_100mb.ORDERS
ADD FOREIGN KEY (O_CUSTKEY) REFERENCES tpch.CUSTOMER(C_CUSTKEY);

-- For table LINEITEM
#ALTER TABLE tpch_100mb.LINEITEM
#ADD FOREIGN KEY (L_ORDERKEY) REFERENCES tpch.ORDERS(O_ORDERKEY),
#ADD FOREIGN KEY (L_PARTKEY,L_SUPPKEY) REFERENCES tpch.PARTSUPP(PS_PARTKEY,PS_SUPPKEY);

